"""A chat turn records how many tokens it was sent.

The provider reports it on every call, the way it reports what a call cost —
which `chain_steps.cost` already keeps. Without it, "what does a turn cost" had
one answer, in a docstring, measured once on a portfolio that no longer existed
and on a prompt that had grown by half since. A figure about a turn belongs to
the turn.

Nullable, and null is the honest value for every turn already on record as well
as for any provider that does not report usage: a zero would be a measurement.

Autogenerate also proposed dropping `instruments_fts` and its five shadow
tables — the catalogue's FTS5 index, which is created by `catalogue._ensure_fts`
and is in no model's metadata, so every autogenerated revision will keep
proposing it. Dropping it would empty the instrument picker's catalogue lane.
Not included here, and not to be pasted back in.

Revision ID: 11d7cc20e53e
Revises: 01f722f11058
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "11d7cc20e53e"
down_revision = "01f722f11058"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("chat_messages") as batch:
        batch.add_column(sa.Column("prompt_tokens", sa.Integer(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("chat_messages") as batch:
        batch.drop_column("prompt_tokens")
