"""composition cache + advisor report kind

Revision ID: 186f8308b0d4
Revises: ab31d0445a54
Create Date: 2026-08-20 19:49:04.994686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186f8308b0d4'
down_revision: Union[str, Sequence[str], None] = 'ab31d0445a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composition_cache',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('resolved_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    with op.batch_alter_table('advisor_reports', schema=None) as batch_op:
        # server_default so existing rows (all whole-picture analyses) get
        # kind='full' when the NOT NULL column lands.
        batch_op.add_column(
            sa.Column('kind', sa.String(), nullable=False, server_default='full')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_reports', schema=None) as batch_op:
        batch_op.drop_column('kind')

    op.drop_table('composition_cache')
    # ### end Alembic commands ###
