"""baseline: full schema

Revision ID: 44ebdc572195
Revises: 
Create Date: 2026-06-09 19:48:54.400721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ebdc572195'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('target_date', sa.String(), nullable=True),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('monthly_contribution', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('acquisition_date', sa.String(), nullable=True),
    sa.Column('acquisition_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_key')
    )
    op.create_table('cash_anchors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'date', name='uq_cash_anchor_institution_date')
    )
    with op.batch_alter_table('cash_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_anchors_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_anchors_institution_id'), ['institution_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_institution_id'), ['institution_id'], unique=False)

    op.create_table('income_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_sources_institution_id'), ['institution_id'], unique=False)

    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('real_asset_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['real_asset_id'], ['real_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liabilities_real_asset_id'), ['real_asset_id'], unique=False)

    op.create_table('real_asset_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['real_asset_id'], ['real_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_asset_id', 'date', name='uq_valuation_asset_date')
    )
    with op.batch_alter_table('real_asset_valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_real_asset_valuations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_real_asset_valuations_real_asset_id'), ['real_asset_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'date', name='uq_snapshot_institution_date')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_institution_id'), ['institution_id'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('from_institution_id', sa.Integer(), nullable=True),
    sa.Column('to_institution_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_from_institution_id'), ['from_institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_to_institution_id'), ['to_institution_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('liability_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liability_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['liability_id'], ['liabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liability_id', 'date', name='uq_balance_liability_date')
    )
    with op.batch_alter_table('liability_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liability_balances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_liability_balances_liability_id'), ['liability_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liability_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liability_balances_liability_id'))
        batch_op.drop_index(batch_op.f('ix_liability_balances_date'))

    op.drop_table('liability_balances')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_snapshot_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_to_institution_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_from_institution_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_date'))

    op.drop_table('transfers')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_institution_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_date'))

    op.drop_table('snapshots')
    with op.batch_alter_table('real_asset_valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_real_asset_valuations_real_asset_id'))
        batch_op.drop_index(batch_op.f('ix_real_asset_valuations_date'))

    op.drop_table('real_asset_valuations')
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liabilities_real_asset_id'))

    op.drop_table('liabilities')
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_sources_institution_id'))

    op.drop_table('income_sources')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_institution_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('cash_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_anchors_institution_id'))
        batch_op.drop_index(batch_op.f('ix_cash_anchors_date'))

    op.drop_table('cash_anchors')
    op.drop_table('survey_responses')
    op.drop_table('settings')
    op.drop_table('real_assets')
    op.drop_table('institutions')
    op.drop_table('goals')
    # ### end Alembic commands ###
