"""advisor_reports (saved analyses)

Revision ID: 4b120214f7e5
Revises: 4c93228b7fd1
Create Date: 2026-06-25 22:50:30.559241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b120214f7e5'
down_revision: Union[str, Sequence[str], None] = '4c93228b7fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advisor_reports')
    # ### end Alembic commands ###
