"""holding distribution_policy (acc/dist)

Revision ID: 4c93228b7fd1
Revises: 44ebdc572195
Create Date: 2026-06-14 17:32:07.833030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c93228b7fd1'
down_revision: Union[str, Sequence[str], None] = '44ebdc572195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_policy', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_column('distribution_policy')

    # ### end Alembic commands ###
