"""price cache

Revision ID: 50c824d3c797
Revises: 645f3090d55a
Create Date: 2026-08-09 19:59:30.101816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c824d3c797'
down_revision: Union[str, Sequence[str], None] = '645f3090d55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_cache')
    # ### end Alembic commands ###
