"""accumulation_plans (PAC)

Revision ID: 645f3090d55a
Revises: 4b120214f7e5
Create Date: 2026-06-25 23:20:27.743989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645f3090d55a'
down_revision: Union[str, Sequence[str], None] = '4b120214f7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accumulation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('source_institution_id', sa.Integer(), nullable=True),
    sa.Column('target_institution_id', sa.Integer(), nullable=True),
    sa.Column('target_symbol', sa.String(), nullable=True),
    sa.Column('target_asset_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accumulation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accumulation_plans_source_institution_id'), ['source_institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accumulation_plans_target_institution_id'), ['target_institution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accumulation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accumulation_plans_target_institution_id'))
        batch_op.drop_index(batch_op.f('ix_accumulation_plans_source_institution_id'))

    op.drop_table('accumulation_plans')
    # ### end Alembic commands ###
