"""pac target isin and transaction isin

Revision ID: 86dd2a380597
Revises: a46fcb737c0b
Create Date: 2026-08-22 23:24:55.230297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86dd2a380597'
down_revision: Union[str, Sequence[str], None] = 'a46fcb737c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accumulation_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_isin', sa.String(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isin', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('isin')

    with op.batch_alter_table('accumulation_plans', schema=None) as batch_op:
        batch_op.drop_column('target_isin')

    # ### end Alembic commands ###
