"""transactions ledger + plan execution mode

Revision ID: ab31d0445a54
Revises: 50c824d3c797
Create Date: 2026-08-09 23:12:00.171008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab31d0445a54'
down_revision: Union[str, Sequence[str], None] = '50c824d3c797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('cash_institution_id', sa.Integer(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_occurrence', sa.String(), nullable=True),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cash_institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['accumulation_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_symbol'), ['symbol'], unique=False)

    with op.batch_alter_table('accumulation_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accumulation_plans', schema=None) as batch_op:
        batch_op.drop_column('execution')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_symbol'))
        batch_op.drop_index(batch_op.f('ix_transactions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_institution_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))

    op.drop_table('transactions')
    # ### end Alembic commands ###
