"""advisor chain runs and steps

Revision ID: b7c6d5f8bd7c
Revises: f01a59d0d830
Create Date: 2026-08-22 17:23:28.080738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c6d5f8bd7c'
down_revision: Union[str, Sequence[str], None] = 'f01a59d0d830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['chain_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chain_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_steps_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chain_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_steps_run_id'))

    op.drop_table('chain_steps')
    op.drop_table('chain_runs')
    # ### end Alembic commands ###
