"""fx rates + price cache currency

Revision ID: f01a59d0d830
Revises: 186f8308b0d4
Create Date: 2026-08-20 20:38:20.465707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01a59d0d830'
down_revision: Union[str, Sequence[str], None] = '186f8308b0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('currency')
    )
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.drop_column('currency')

    op.drop_table('fx_rates')
    # ### end Alembic commands ###
